In [5]:
import nltk
import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer,WordNetLemmatizer

In [2]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\shakthi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shakthi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
with open(r'random_collocation_text.txt','r') as f:
    content=f.read()
    l=content.split("\n")
    for i in l:
        if i=="":
            l.remove("")

print(l)

['The language science applies patterns effectively.', 'The data application implements patterns effectively.', 'The language system implements patterns effectively.', 'The machine learning analyzes patterns effectively.', 'The machine learning applies patterns effectively.', 'The deep analysis analyzes patterns effectively.', 'The big model predicts patterns effectively.', 'The deep application develops patterns effectively.', 'The social network analyzes patterns effectively.', 'The predictive technology predicts patterns effectively.', 'The deep analysis develops patterns effectively.', 'The language analysis applies patterns effectively.', 'The data pattern integrates patterns effectively.', 'The deep learning applies patterns effectively.', 'The neural network implements patterns effectively.', 'The neural analysis predicts patterns effectively.', 'The statistical science applies patterns effectively.', 'The data network learns patterns effectively.', 'The deep analysis develops patterns effectively.', 'The big pattern analyzes patterns effectively.', 'The big science predicts patterns effectively.', 'The big application implements patterns effectively.', 'The language technology implements patterns effectively.', 'The data processing learns patterns effectively.', 'The text application analyzes patterns effectively.', 'The deep learning applies patterns effectively.', 'The deep analysis develops patterns effectively.', 'The statistical learning implements patterns effectively.', 'The deep technology develops patterns effectively.', 'The text processing uses patterns effectively.', 'The social system optimizes patterns effectively.', 'The deep science improves patterns effectively.', 'The deep technology uses patterns effectively.', 'The text application implements patterns effectively.', 'The social science uses patterns effectively.', 'The deep learning learns patterns effectively.', 'The social learning learns patterns effectively.', 'The machine system integrates patterns effectively.', 'The machine pattern optimizes patterns effectively.', 'The big technology predicts patterns effectively.', 'The big learning predicts patterns effectively.', 'The deep technology improves patterns effectively.', 'The big science improves patterns effectively.', 'The statistical application analyzes patterns effectively.', 'The big processing learns patterns effectively.', 'The data application analyzes patterns effectively.', 'The deep processing improves patterns effectively.', 'The predictive pattern learns patterns effectively.', 'The machine science integrates patterns effectively.', 'The language model implements patterns effectively.', 'The neural pattern improves patterns effectively.', 'The machine processing learns patterns effectively.', 'The big model optimizes patterns effectively.', 'The machine system predicts patterns effectively.', 'The big network integrates patterns effectively.', 'The language technology implements patterns effectively.', 'The deep pattern uses patterns effectively.', 'The deep science analyzes patterns effectively.', 'The text learning implements patterns effectively.', 'The social application integrates patterns effectively.', 'The machine technology predicts patterns effectively.', 'The data model uses patterns effectively.', 'The language pattern implements patterns effectively.', 'The social learning integrates patterns effectively.', 'The predictive learning uses patterns effectively.', 'The neural model improves patterns effectively.', 'The predictive learning learns patterns effectively.', 'The statistical pattern applies patterns effectively.', 'The machine processing integrates patterns effectively.', 'The neural technology improves patterns effectively.', 'The big system develops patterns effectively.', 'The text learning develops patterns effectively.', 'The data learning integrates patterns effectively.', 'The deep model improves patterns effectively.', 'The language model improves patterns effectively.', 'The statistical network analyzes patterns effectively.', 'The text pattern optimizes patterns effectively.', 'The machine learning uses patterns effectively.', 'The big learning analyzes patterns effectively.', 'The predictive processing implements patterns effectively.', 'The neural analysis optimizes patterns effectively.', 'The social learning improves patterns effectively.', 'The language science improves patterns effectively.', 'The big network optimizes patterns effectively.', 'The social learning improves patterns effectively.', 'The neural system develops patterns effectively.', 'The machine network improves patterns effectively.', 'The statistical processing develops patterns effectively.', 'The data science uses patterns effectively.', 'The social application applies patterns effectively.', 'The deep technology predicts patterns effectively.', 'The neural pattern optimizes patterns effectively.', 'The statistical pattern predicts patterns effectively.', 'The neural system improves patterns effectively.', 'The deep learning develops patterns effectively.', 'The social processing uses patterns effectively.', 'The social technology learns patterns effectively.', 'The big network optimizes patterns effectively.', 'The text learning optimizes patterns effectively.', 'The data analysis learns patterns effectively.']

In [6]:
df=pd.DataFrame({"Text":l})
df.head()

                                                Text
0  The language science applies patterns effectiv...
1  The data application implements patterns effec...
2  The language system implements patterns effect...
3  The machine learning analyzes patterns effecti...
4  The machine learning applies patterns effectiv...

In [10]:
def preprocess(text,stemming=True):
    tokens=word_tokenize(text)
    stop_words=set(stopwords.words('english'))
    tokens= [token for token in tokens if token.lower() not in stop_words]

    if stemming:
        stemmer=PorterStemmer()
        tokens=[stemmer.stem(token) for token in tokens]
    else:
        Lemmatizer=WordNetLemmatizer()
        tokens=[Lemmatizer.lemmatize(token) for token in tokens]

    print(tokens)
    return tokens

In [11]:
df['Preprocessed']=df['Text'].apply(preprocess)

['languag', 'scienc', 'appli', 'pattern', 'effect', '.']
['data', 'applic', 'implement', 'pattern', 'effect', '.']
['languag', 'system', 'implement', 'pattern', 'effect', '.']
['machin', 'learn', 'analyz', 'pattern', 'effect', '.']
['machin', 'learn', 'appli', 'pattern', 'effect', '.']
['deep', 'analysi', 'analyz', 'pattern', 'effect', '.']
['big', 'model', 'predict', 'pattern', 'effect', '.']
['deep', 'applic', 'develop', 'pattern', 'effect', '.']
['social', 'network', 'analyz', 'pattern', 'effect', '.']
['predict', 'technolog', 'predict', 'pattern', 'effect', '.']
['deep', 'analysi', 'develop', 'pattern', 'effect', '.']
['languag', 'analysi', 'appli', 'pattern', 'effect', '.']
['data', 'pattern', 'integr', 'pattern', 'effect', '.']
['deep', 'learn', 'appli', 'pattern', 'effect', '.']
['neural', 'network', 'implement', 'pattern', 'effect', '.']
['neural', 'analysi', 'predict', 'pattern', 'effect', '.']
['statist', 'scienc', 'appli', 'pattern', 'effect', '.']
['data', 'network', 'learn', 'pattern', 'effect', '.']
['deep', 'analysi', 'develop', 'pattern', 'effect', '.']
['big', 'pattern', 'analyz', 'pattern', 'effect', '.']
['big', 'scienc', 'predict', 'pattern', 'effect', '.']
['big', 'applic', 'implement', 'pattern', 'effect', '.']
['languag', 'technolog', 'implement', 'pattern', 'effect', '.']
['data', 'process', 'learn', 'pattern', 'effect', '.']
['text', 'applic', 'analyz', 'pattern', 'effect', '.']
['deep', 'learn', 'appli', 'pattern', 'effect', '.']
['deep', 'analysi', 'develop', 'pattern', 'effect', '.']
['statist', 'learn', 'implement', 'pattern', 'effect', '.']
['deep', 'technolog', 'develop', 'pattern', 'effect', '.']
['text', 'process', 'use', 'pattern', 'effect', '.']
['social', 'system', 'optim', 'pattern', 'effect', '.']
['deep', 'scienc', 'improv', 'pattern', 'effect', '.']
['deep', 'technolog', 'use', 'pattern', 'effect', '.']
['text', 'applic', 'implement', 'pattern', 'effect', '.']
['social', 'scienc', 'use', 'pattern', 'effect', '.']
['deep', 'learn', 'learn', 'pattern', 'effect', '.']
['social', 'learn', 'learn', 'pattern', 'effect', '.']
['machin', 'system', 'integr', 'pattern', 'effect', '.']
['machin', 'pattern', 'optim', 'pattern', 'effect', '.']
['big', 'technolog', 'predict', 'pattern', 'effect', '.']
['big', 'learn', 'predict', 'pattern', 'effect', '.']
['deep', 'technolog', 'improv', 'pattern', 'effect', '.']
['big', 'scienc', 'improv', 'pattern', 'effect', '.']
['statist', 'applic', 'analyz', 'pattern', 'effect', '.']
['big', 'process', 'learn', 'pattern', 'effect', '.']
['data', 'applic', 'analyz', 'pattern', 'effect', '.']
['deep', 'process', 'improv', 'pattern', 'effect', '.']
['predict', 'pattern', 'learn', 'pattern', 'effect', '.']
['machin', 'scienc', 'integr', 'pattern', 'effect', '.']
['languag', 'model', 'implement', 'pattern', 'effect', '.']
['neural', 'pattern', 'improv', 'pattern', 'effect', '.']
['machin', 'process', 'learn', 'pattern', 'effect', '.']
['big', 'model', 'optim', 'pattern', 'effect', '.']
['machin', 'system', 'predict', 'pattern', 'effect', '.']
['big', 'network', 'integr', 'pattern', 'effect', '.']
['languag', 'technolog', 'implement', 'pattern', 'effect', '.']
['deep', 'pattern', 'use', 'pattern', 'effect', '.']
['deep', 'scienc', 'analyz', 'pattern', 'effect', '.']
['text', 'learn', 'implement', 'pattern', 'effect', '.']
['social', 'applic', 'integr', 'pattern', 'effect', '.']
['machin', 'technolog', 'predict', 'pattern', 'effect', '.']
['data', 'model', 'use', 'pattern', 'effect', '.']
['languag', 'pattern', 'implement', 'pattern', 'effect', '.']
['social', 'learn', 'integr', 'pattern', 'effect', '.']
['predict', 'learn', 'use', 'pattern', 'effect', '.']
['neural', 'model', 'improv', 'pattern', 'effect', '.']
['predict', 'learn', 'learn', 'pattern', 'effect', '.']
['statist', 'pattern', 'appli', 'pattern', 'effect', '.']
['machin', 'process', 'integr', 'pattern', 'effect', '.']
['neural', 'technolog', 'improv', 'pattern', 'effect', '.']
['big', 'system', 'develop', 'pattern', 'effect', '.']
['text', 'learn', 'develop', 'pattern', 'effect', '.']
['data', 'learn', 'integr', 'pattern', 'effect', '.']
['deep', 'model', 'improv', 'pattern', 'effect', '.']
['languag', 'model', 'improv', 'pattern', 'effect', '.']
['statist', 'network', 'analyz', 'pattern', 'effect', '.']
['text', 'pattern', 'optim', 'pattern', 'effect', '.']
['machin', 'learn', 'use', 'pattern', 'effect', '.']
['big', 'learn', 'analyz', 'pattern', 'effect', '.']
['predict', 'process', 'implement', 'pattern', 'effect', '.']
['neural', 'analysi', 'optim', 'pattern', 'effect', '.']
['social', 'learn', 'improv', 'pattern', 'effect', '.']
['languag', 'scienc', 'improv', 'pattern', 'effect', '.']
['big', 'network', 'optim', 'pattern', 'effect', '.']
['social', 'learn', 'improv', 'pattern', 'effect', '.']
['neural', 'system', 'develop', 'pattern', 'effect', '.']
['machin', 'network', 'improv', 'pattern', 'effect', '.']
['statist', 'process', 'develop', 'pattern', 'effect', '.']
['data', 'scienc', 'use', 'pattern', 'effect', '.']
['social', 'applic', 'appli', 'pattern', 'effect', '.']
['deep', 'technolog', 'predict', 'pattern', 'effect', '.']
['neural', 'pattern', 'optim', 'pattern', 'effect', '.']
['statist', 'pattern', 'predict', 'pattern', 'effect', '.']
['neural', 'system', 'improv', 'pattern', 'effect', '.']
['deep', 'learn', 'develop', 'pattern', 'effect', '.']
['social', 'process', 'use', 'pattern', 'effect', '.']
['social', 'technolog', 'learn', 'pattern', 'effect', '.']
['big', 'network', 'optim', 'pattern', 'effect', '.']
['text', 'learn', 'optim', 'pattern', 'effect', '.']
['data', 'analysi', 'learn', 'pattern', 'effect', '.']

In [12]:
df.head()

,Text,Preprocessed
0,The language science applies patterns effectiv...,"[languag, scienc, appli, pattern, effect, .]"
1,The data application implements patterns effec...,"[data, applic, implement, pattern, effect, .]"
2,The language system implements patterns effect...,"[languag, system, implement, pattern, effect, .]"
3,The machine learning analyzes patterns effecti...,"[machin, learn, analyz, pattern, effect, .]"
4,The machine learning applies patterns effectiv...,"[machin, learn, appli, pattern, effect, .]"

In [13]:
l=[]
for i in df['Preprocessed']:
    for j in i:
        if j!="":
            l.append(j)
print(l)

['languag', 'scienc', 'appli', 'pattern', 'effect', '.', 'data', 'applic', 'implement', 'pattern', 'effect', '.', 'languag', 'system', 'implement', 'pattern', 'effect', '.', 'machin', 'learn', 'analyz', 'pattern', 'effect', '.', 'machin', 'learn', 'appli', 'pattern', 'effect', '.', 'deep', 'analysi', 'analyz', 'pattern', 'effect', '.', 'big', 'model', 'predict', 'pattern', 'effect', '.', 'deep', 'applic', 'develop', 'pattern', 'effect', '.', 'social', 'network', 'analyz', 'pattern', 'effect', '.', 'predict', 'technolog', 'predict', 'pattern', 'effect', '.', 'deep', 'analysi', 'develop', 'pattern', 'effect', '.', 'languag', 'analysi', 'appli', 'pattern', 'effect', '.', 'data', 'pattern', 'integr', 'pattern', 'effect', '.', 'deep', 'learn', 'appli', 'pattern', 'effect', '.', 'neural', 'network', 'implement', 'pattern', 'effect', '.', 'neural', 'analysi', 'predict', 'pattern', 'effect', '.', 'statist', 'scienc', 'appli', 'pattern', 'effect', '.', 'data', 'network', 'learn', 'pattern', 'effect', '.', 'deep', 'analysi', 'develop', 'pattern', 'effect', '.', 'big', 'pattern', 'analyz', 'pattern', 'effect', '.', 'big', 'scienc', 'predict', 'pattern', 'effect', '.', 'big', 'applic', 'implement', 'pattern', 'effect', '.', 'languag', 'technolog', 'implement', 'pattern', 'effect', '.', 'data', 'process', 'learn', 'pattern', 'effect', '.', 'text', 'applic', 'analyz', 'pattern', 'effect', '.', 'deep', 'learn', 'appli', 'pattern', 'effect', '.', 'deep', 'analysi', 'develop', 'pattern', 'effect', '.', 'statist', 'learn', 'implement', 'pattern', 'effect', '.', 'deep', 'technolog', 'develop', 'pattern', 'effect', '.', 'text', 'process', 'use', 'pattern', 'effect', '.', 'social', 'system', 'optim', 'pattern', 'effect', '.', 'deep', 'scienc', 'improv', 'pattern', 'effect', '.', 'deep', 'technolog', 'use', 'pattern', 'effect', '.', 'text', 'applic', 'implement', 'pattern', 'effect', '.', 'social', 'scienc', 'use', 'pattern', 'effect', '.', 'deep', 'learn', 'learn', 'pattern', 'effect', '.', 'social', 'learn', 'learn', 'pattern', 'effect', '.', 'machin', 'system', 'integr', 'pattern', 'effect', '.', 'machin', 'pattern', 'optim', 'pattern', 'effect', '.', 'big', 'technolog', 'predict', 'pattern', 'effect', '.', 'big', 'learn', 'predict', 'pattern', 'effect', '.', 'deep', 'technolog', 'improv', 'pattern', 'effect', '.', 'big', 'scienc', 'improv', 'pattern', 'effect', '.', 'statist', 'applic', 'analyz', 'pattern', 'effect', '.', 'big', 'process', 'learn', 'pattern', 'effect', '.', 'data', 'applic', 'analyz', 'pattern', 'effect', '.', 'deep', 'process', 'improv', 'pattern', 'effect', '.', 'predict', 'pattern', 'learn', 'pattern', 'effect', '.', 'machin', 'scienc', 'integr', 'pattern', 'effect', '.', 'languag', 'model', 'implement', 'pattern', 'effect', '.', 'neural', 'pattern', 'improv', 'pattern', 'effect', '.', 'machin', 'process', 'learn', 'pattern', 'effect', '.', 'big', 'model', 'optim', 'pattern', 'effect', '.', 'machin', 'system', 'predict', 'pattern', 'effect', '.', 'big', 'network', 'integr', 'pattern', 'effect', '.', 'languag', 'technolog', 'implement', 'pattern', 'effect', '.', 'deep', 'pattern', 'use', 'pattern', 'effect', '.', 'deep', 'scienc', 'analyz', 'pattern', 'effect', '.', 'text', 'learn', 'implement', 'pattern', 'effect', '.', 'social', 'applic', 'integr', 'pattern', 'effect', '.', 'machin', 'technolog', 'predict', 'pattern', 'effect', '.', 'data', 'model', 'use', 'pattern', 'effect', '.', 'languag', 'pattern', 'implement', 'pattern', 'effect', '.', 'social', 'learn', 'integr', 'pattern', 'effect', '.', 'predict', 'learn', 'use', 'pattern', 'effect', '.', 'neural', 'model', 'improv', 'pattern', 'effect', '.', 'predict', 'learn', 'learn', 'pattern', 'effect', '.', 'statist', 'pattern', 'appli', 'pattern', 'effect', '.', 'machin', 'process', 'integr', 'pattern', 'effect', '.', 'neural', 'technolog', 'improv', 'pattern', 'effect', '.', 'big', 'system', 'develop', 'pattern', 'effect', '.', 'text', 'learn', 'develop', 'pattern', 'effect', '.', 'data', 'learn', 'integr', 'pattern', 'effect', '.', 'deep', 'model', 'improv', 'pattern', 'effect', '.', 'languag', 'model', 'improv', 'pattern', 'effect', '.', 'statist', 'network', 'analyz', 'pattern', 'effect', '.', 'text', 'pattern', 'optim', 'pattern', 'effect', '.', 'machin', 'learn', 'use', 'pattern', 'effect', '.', 'big', 'learn', 'analyz', 'pattern', 'effect', '.', 'predict', 'process', 'implement', 'pattern', 'effect', '.', 'neural', 'analysi', 'optim', 'pattern', 'effect', '.', 'social', 'learn', 'improv', 'pattern', 'effect', '.', 'languag', 'scienc', 'improv', 'pattern', 'effect', '.', 'big', 'network', 'optim', 'pattern', 'effect', '.', 'social', 'learn', 'improv', 'pattern', 'effect', '.', 'neural', 'system', 'develop', 'pattern', 'effect', '.', 'machin', 'network', 'improv', 'pattern', 'effect', '.', 'statist', 'process', 'develop', 'pattern', 'effect', '.', 'data', 'scienc', 'use', 'pattern', 'effect', '.', 'social', 'applic', 'appli', 'pattern', 'effect', '.', 'deep', 'technolog', 'predict', 'pattern', 'effect', '.', 'neural', 'pattern', 'optim', 'pattern', 'effect', '.', 'statist', 'pattern', 'predict', 'pattern', 'effect', '.', 'neural', 'system', 'improv', 'pattern', 'effect', '.', 'deep', 'learn', 'develop', 'pattern', 'effect', '.', 'social', 'process', 'use', 'pattern', 'effect', '.', 'social', 'technolog', 'learn', 'pattern', 'effect', '.', 'big', 'network', 'optim', 'pattern', 'effect', '.', 'text', 'learn', 'optim', 'pattern', 'effect', '.', 'data', 'analysi', 'learn', 'pattern', 'effect', '.']

In [15]:
text="".join(l)
vocab=set(l)
n=len(vocab)
n

30

In [19]:
unigram_dict={}
bigram_dict={}
for i in range(len(l)-1):
    if l[i] not in unigram_dict.keys():
        unigram_dict[l[i]]=1
    else:
        unigram_dict[l[i]]+=1
    bigram=(l[i],l[i+1])
    if bigram not in bigram_dict.keys():
        bigram_dict[bigram]=1
    else:
        bigram_dict[bigram]+=1
unigram_dict

{'languag': 9,
 'scienc': 10,
 'appli': 8,
 'pattern': 111,
 'effect': 100,
 '.': 99,
 'data': 9,
 'applic': 9,
 'implement': 12,
 'system': 7,
 'machin': 11,
 'learn': 30,
 'analyz': 10,
 'deep': 18,
 'analysi': 8,
 'big': 14,
 'model': 7,
 'predict': 15,
 'develop': 10,
 'social': 11,
 'network': 8,
 'technolog': 11,
 'integr': 8,
 'neural': 9,
 'statist': 7,
 'process': 9,
 'text': 7,
 'use': 9,
 'optim': 9,
 'improv': 14}

In [20]:
bigram_dict

{('languag', 'scienc'): 2,
 ('scienc', 'appli'): 2,
 ('appli', 'pattern'): 8,
 ('pattern', 'effect'): 100,
 ('effect', '.'): 100,
 ('.', 'data'): 9,
 ('data', 'applic'): 2,
 ('applic', 'implement'): 3,
 ('implement', 'pattern'): 12,
 ('.', 'languag'): 8,
 ('languag', 'system'): 1,
 ('system', 'implement'): 1,
 ('.', 'machin'): 11,
 ('machin', 'learn'): 3,
 ('learn', 'analyz'): 2,
 ('analyz', 'pattern'): 10,
 ('learn', 'appli'): 3,
 ('.', 'deep'): 18,
 ('deep', 'analysi'): 4,
 ('analysi', 'analyz'): 1,
 ('.', 'big'): 14,
 ('big', 'model'): 2,
 ('model', 'predict'): 1,
 ('predict', 'pattern'): 11,
 ('deep', 'applic'): 1,
 ('applic', 'develop'): 1,
 ('develop', 'pattern'): 10,
 ('.', 'social'): 11,
 ('social', 'network'): 1,
 ('network', 'analyz'): 2,
 ('.', 'predict'): 5,
 ('predict', 'technolog'): 1,
 ('technolog', 'predict'): 4,
 ('analysi', 'develop'): 3,
 ('languag', 'analysi'): 1,
 ('analysi', 'appli'): 1,
 ('data', 'pattern'): 1,
 ('pattern', 'integr'): 1,
 ('integr', 'pattern'): 8,
 ('deep', 'learn'): 4,
 ('.', 'neural'): 9,
 ('neural', 'network'): 1,
 ('network', 'implement'): 1,
 ('neural', 'analysi'): 2,
 ('analysi', 'predict'): 1,
 ('.', 'statist'): 7,
 ('statist', 'scienc'): 1,
 ('data', 'network'): 1,
 ('network', 'learn'): 1,
 ('learn', 'pattern'): 10,
 ('big', 'pattern'): 1,
 ('pattern', 'analyz'): 1,
 ('big', 'scienc'): 2,
 ('scienc', 'predict'): 1,
 ('big', 'applic'): 1,
 ('languag', 'technolog'): 2,
 ('technolog', 'implement'): 2,
 ('data', 'process'): 1,
 ('process', 'learn'): 3,
 ('.', 'text'): 7,
 ('text', 'applic'): 2,
 ('applic', 'analyz'): 3,
 ('statist', 'learn'): 1,
 ('learn', 'implement'): 2,
 ('deep', 'technolog'): 4,
 ('technolog', 'develop'): 1,
 ('text', 'process'): 1,
 ('process', 'use'): 2,
 ('use', 'pattern'): 9,
 ('social', 'system'): 1,
 ('system', 'optim'): 1,
 ('optim', 'pattern'): 9,
 ('deep', 'scienc'): 2,
 ('scienc', 'improv'): 3,
 ('improv', 'pattern'): 14,
 ('technolog', 'use'): 1,
 ('social', 'scienc'): 1,
 ('scienc', 'use'): 2,
 ('learn', 'learn'): 3,
 ('social', 'learn'): 4,
 ('machin', 'system'): 2,
 ('system', 'integr'): 1,
 ('machin', 'pattern'): 1,
 ('pattern', 'optim'): 3,
 ('big', 'technolog'): 1,
 ('big', 'learn'): 2,
 ('learn', 'predict'): 1,
 ('technolog', 'improv'): 2,
 ('statist', 'applic'): 1,
 ('big', 'process'): 1,
 ('deep', 'process'): 1,
 ('process', 'improv'): 1,
 ('pattern', 'learn'): 1,
 ('machin', 'scienc'): 1,
 ('scienc', 'integr'): 1,
 ('languag', 'model'): 2,
 ('model', 'implement'): 1,
 ('neural', 'pattern'): 2,
 ('pattern', 'improv'): 1,
 ('machin', 'process'): 2,
 ('model', 'optim'): 1,
 ('system', 'predict'): 1,
 ('big', 'network'): 3,
 ('network', 'integr'): 1,
 ('deep', 'pattern'): 1,
 ('pattern', 'use'): 1,
 ('scienc', 'analyz'): 1,
 ('text', 'learn'): 3,
 ('social', 'applic'): 2,
 ('applic', 'integr'): 1,
 ('machin', 'technolog'): 1,
 ('data', 'model'): 1,
 ('model', 'use'): 1,
 ('languag', 'pattern'): 1,
 ('pattern', 'implement'): 1,
 ('learn', 'integr'): 2,
 ('predict', 'learn'): 2,
 ('learn', 'use'): 2,
 ('neural', 'model'): 1,
 ('model', 'improv'): 3,
 ('statist', 'pattern'): 2,
 ('pattern', 'appli'): 1,
 ('process', 'integr'): 1,
 ('neural', 'technolog'): 1,
 ('big', 'system'): 1,
 ('system', 'develop'): 2,
 ('learn', 'develop'): 2,
 ('data', 'learn'): 1,
 ('deep', 'model'): 1,
 ('statist', 'network'): 1,
 ('text', 'pattern'): 1,
 ('predict', 'process'): 1,
 ('process', 'implement'): 1,
 ('analysi', 'optim'): 1,
 ('learn', 'improv'): 2,
 ('network', 'optim'): 2,
 ('neural', 'system'): 2,
 ('machin', 'network'): 1,
 ('network', 'improv'): 1,
 ('statist', 'process'): 1,
 ('process', 'develop'): 1,
 ('data', 'scienc'): 1,
 ('applic', 'appli'): 1,
 ('pattern', 'predict'): 1,
 ('system', 'improv'): 1,
 ('social', 'process'): 1,
 ('social', 'technolog'): 1,
 ('technolog', 'learn'): 1,
 ('learn', 'optim'): 1,
 ('data', 'analysi'): 1,
 ('analysi', 'learn'): 1}

In [21]:
len(bigram_dict)

151

In [25]:
import math
def t_test_collocation(unigram_counts,bigram_counts,word1,word2,total_count):
    count_word1=unigram_counts.get(word1,0.00000000001)
    count_word2=unigram_counts.get(word2,0.000000000001)
    bigram_count=bigram_counts.get((word1,word2),0.00000000000001)

    expected_freq=(count_word1+count_word2)/total_count

    variance_word1 = sum((freq - count_word1) ** 2 for freq in unigram_counts.values()) / (len(unigram_counts) - 1)
    variance_word2=sum((freq-count_word2)**2 for freq in unigram_counts.values())/(len(unigram_counts)-1)

    standard_error = math.sqrt(variance_word1 / count_word1 + variance_word2 / count_word2)
    standard_error = math.sqrt(variance_word1 / count_word1 + variance_word2 / count_word2)
    
    # t-statistic
    t_stat = (bigram_count - expected_freq) / standard_error   #t=(x-u)/(se)
    
    return t_stat


t_test_collocation(unigram_dict,bigram_dict,"pradeepa","niggi",len(bigram_dict))

-1.7057569114821907e-21

In [26]:
def chi_square_test(word1,word2,bigram_dict,unigram_dict,total_counts):
    o11=bigram_counts.get((word1,word2),0.000000000001)
    o12=unigram_counts.get(word1,0.00000000000000001)-o11
    o21=unigram_counts.get(word2,0.00000000000000000001)-o11
    o22=total_count-unigram_counts.get(word1,0.00000000000000001)-unigram_counts.get(word2,0.00000000000000000001)

    e11 = (unigram_dict.get(word1, 0.01) * unigram_dict.get(word2, 0.01)) / total_count
    e12 = (unigram_dict.get(word1, 0.01) * (total_count - unigram_dict.get(word2, 0.01))) / total_count
    e21 = ((total_count - unigram_dict.get(word1, 0.01)) * unigram_dict.get(word2, 0.01)) / total_count
    e22 = ((total_count - unigram_dict.get(word1, 0.01)) * (total_count - unigram_dict.get(word2, 0.01))) / total_count

SyntaxError: incomplete input (653178975.py, line 1)