In [2]:
import nltk
import math
import random 
import pandas as pd
import numpy as np

In [10]:
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag  # Corrected import for pos_tag
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.collocations import BigramAssocMeasures, BigramCollocationFinder
from collections import defaultdict
from scipy import stats

In [14]:
df=pd.read_csv(r"C:\Users\shakthi\Downloads\archive\Valid.csv")
df.head()

                                                text  label
0  It's been about 14 years since Sharon Stone aw...      0
1  someone needed to make a car payment... this i...      0
2  The Guidelines state that a comment must conta...      0
3  This movie is a muddled mish-mash of clichés f...      0
4  Before Stan Laurel became the smaller half of ...      0

In [16]:
l=list(df.columns)
l

['text', 'label']

In [17]:
df.drop(df[l],inplace=True,axis=1)
df.head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [18]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\shakthi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shakthi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\shakthi\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [19]:
def preprocess_text(text,use_stemmer=True):
    words = word_tokenize(text.lower())
    stopwords = set(stopwords.words('english'))
    porter_stemmer = PorterStemmer()
    wordnet_lemmatizer = WordNetLemmatizer()
    filtered_words = [word for word in words if word not in stopwords and word.isalpha()]
    
    if use_stemmer:
        stemmed_words = [porter_stemmer.stem(word) for word in words]
        return " ".join(stemmed_words)
    else:
        lemmatized_words = [wordnet_lemmatizer.lemmatize(word) for word in words]
        return " ".join(lemmatized_words)
    
df["Processed_stemmed"]=df['Text'].apply(preprocess_text)
df["Processed_lemmatized"]=df['Text'].apply(lambda x: preprocess_text(x,use_stemmer=False))

KeyError: 'Text'